name: Hexo Deploy

on:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          git config --global user.email "1732373074@qq.com"
          git config --global user.name "ximenxiaoxue"
          git config --global init.defaultBranch main
          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy

      - name: ECS clone Gitee # 连接服务器并克隆Gitee
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.USER_HOST }} # 服务器的 IP 地址
          user: ${{ secrets.USER_NAME }} # 服务器的用户名
          pass: ${{ secrets.USER_PASS }} # 服务器的密码
          connect_timeout: 10s
          script: |
            cd ${{ secrets.ECS_SITE }}
            rm -rf *
            git clone -b master https://gitee.com/${{ secrets.GITEE_USERNAME }}/blog.git
            cd blog
            cp -r . ..
            cd ..
            rm -rf blog
